### ISSUE TITLE
Remove deprecated image slider styles from style.css

### ISSUE THREAD

**Issue by rainow-** [miles-no/miles-wp-theme#51]
Relates to changes in https://github.com/miles-no/miles_web_components/issues/88

This block is no longer needed:

```css
.entry-content miles-image-slider {
    width: 100dvw;
    transform: translateX(-50%);
    position: relative;
    left: 50%;
}
```
